### ISSUE TITLE
Test suite fails when current UTC offset is not -0500

### ISSUE THREAD

**Issue by nclavaud** [headzoo/react-moment#5]
Hi,

Running the test suite here fails:
```
 FAIL  tests/index.js
  react-moment
    ✕ children (34ms)
    ✕ date (6ms)
    ✕ parse (3ms)
    ✓ format (3ms)
    ✓ fromNow (10ms)
    ✓ from (10ms)
    ✓ toNow (10ms)
    ✓ to (10ms)
    ✓ calendar (3ms)
    ✕ unix (3ms)
    ✓ utc (4ms)
    ✓ other (4ms)

  ● react-moment › children

    expect(received).toEqual(expected)
    
    Expected value to equal:
      "Mon Apr 19 1976 12:59:00 GMT-0500"
    Received:
      "Mon Apr 19 1976 17:59:00 GMT+0000"
      
      at Object.<anonymous> (tests/index.js:26:91)

  ● react-moment › date

    expect(received).toEqual(expected)
    
    Expected value to equal:
      "Mon Apr 19 1976 12:59:00 GMT-0500"
    Received:
      "Mon Apr 19 1976 17:59:00 GMT+0000"
      
      at Object.<anonymous> (tests/index.js:44:91)

  ● react-moment › parse

    expect(received).toEqual(expected)
    
    Expected value to equal:
      "Mon Apr 19 1976 12:59:00 GMT-0500"
    Received:
      "Mon Apr 19 1976 12:59:00 GMT+0000"
      
      at Object.<anonymous> (tests/index.js:56:91)

  ● react-moment › unix

    expect(received).toEqual(expected)
    
    Expected value to equal:
      "Mon Apr 19 1976 12:59:00 GMT-0500"
    Received:
      "Mon Apr 19 1976 17:59:00 GMT+0000"
      
      at Object.<anonymous> (tests/index.js:134:91)

Test Summary
 › Ran all tests.
 › 4 tests failed, 8 tests passed (12 total in 1 test suite, run time 1.077s)
```

I guess this has something to do with the UTC offset, either the parsing or the formatting.

**Comment by nclavaud** [comment]
I was running the test suite from a Docker container, using the official `node` image. I managed to make it pass by setting the timezone to `New York`:
```
$ docker run -it --rm -v $PWD:/opt -w /opt -e "TZ=America/New_York" node npm test

 PASS  tests/index.js
  react-moment
    ✓ children (34ms)
    ✓ date (9ms)
    ✓ parse (2ms)
    ✓ format (3ms)
    ✓ fromNow (10ms)
    ✓ from (12ms)
    ✓ toNow (9ms)
    ✓ to (7ms)
    ✓ calendar (5ms)
    ✓ unix (3ms)
    ✓ utc (2ms)
    ✓ other (4ms)

Test Summary
 › Ran all tests.
 › 12 tests passed (12 total in 1 test suite, run time 1.054s)
```

**Comment by headzoo** [comment]
I'm honestly not sure what to do about that. Still giving it some thought.
