### ISSUE TITLE
When updated to 0.8.4, and ran in node test, property 'format' is undefined

### ISSUE THREAD

**Issue by ngbrown** [headzoo/react-moment#83]
I updated from v0.8.2 to v0.8.4 (also checked v0.8.3), and my unit tests now failing with:

```
    TypeError: Cannot set property 'format' of undefined

      at D (node_modules/react-moment/dist/index.js:11:12116)
      at Object.<anonymous> (node_modules/react-moment/dist/index.js:11:13748)
      at node_modules/react-moment/dist/index.js:11:54
      at Object.<anonymous> (node_modules/react-moment/dist/index.js:11:152)
      at t (node_modules/react-moment/dist/index.js:1:470)
      at Object.<anonymous> (node_modules/react-moment/dist/index.js:1:1843)
      at t (node_modules/react-moment/dist/index.js:1:470)
      at node_modules/react-moment/dist/index.js:1:557
      at node_modules/react-moment/dist/index.js:1:562
      at node_modules/react-moment/dist/index.js:1:108
```

I'm running Jest tests with `"testEnviroment": "node"`.  I'm assuming non-DOM usage would also be needed for server-side-rendering.

**Comment by headzoo** [comment]
Closing old open issue during cleanup.
