### ISSUE TITLE
Latest version (>= 0.9.0) breaks server-side rendering

### ISSUE THREAD

**Issue by egges** [headzoo/react-moment#91]
After updating from 0.8.4 to 0.9.x, react-moment breaks server-side rendering since there is a reference to 'window' somewhere in the code. I get the following runtime error:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/dashboard/node_modules/react-moment/dist/index.js:1:374)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at newRequire (/dashboard/dist/server/index.js:34:18)
    at localRequire (/dashboard/dist/server/index.js:53:14)
```

Reverting to v0.8.4 removes the error message.

**Comment by headzoo** [comment]
Thanks for letting me know. I published react-moment@0.9.2 which should fix the problem.
